server:
  port: 0

spring:
  application:
    name: order-service
  # Distributed Tracking
  zipkin:
    base-uri: http://127.0.0.1:9411
    enabled: true
  sleuth:
    sampler:
      probability: 1.0
  #########
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
      path: /h2-console
  # ??? ??? ??? ???? ???? ?? ??
  # sql ?? ???? ???? ?????.
  jpa:
    hibernate:
#      ddl-auto: create-drop
      # change ddl-auto
      ddl-auto: update
    show-sql: true
    generate-ddl: true
  # spring ??? ???? ?? data.sql? ?? ???? ?? ??
  # ??? ?? ?????? ??
#  defer-datasource-initialization: true
  datasource:
    # set mariaDB
    driver-class-name:  org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/msadb
    username: root
    password: 1234
#    driver-class-name: org.h2.Driver
#    url: jdbc:h2:mem:testdb
#    username: sa
#    password: 1234

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

logging:
  level:
    com.example.orderservice: DEBUG

# Welcome Message
greeting:
  message: Welcome to the Simple E-Commerce.

management:
  endpoints:
    web:
      exposure:
        include: refresh,health,beans,httptrace,busrefresh,info,prometheus,metrics