server:
  port: 8888

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Isanghada/MSA_config_repo.git
          # if private repository add command
          # username: [your username]
          # password: [your password]